// AUTH ACTIONS
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// BACKDROP ACTIONS
export const BDROP_SET = 'BDROP_SET';
export const BDROP_UNSET = 'BDROP_UNSET';

// SNACKBAR ACTIONS
export const ALERT_SET = 'ALERT_SET';
export const ALERT_UNSET = 'ALERT_UNSET';
export const ALERT_ERROR = 'ALERT_ERROR';

// FORM ACTIONS
export const FORM_SET_DATA = 'FORM_SET_DATA';
export const FORM_RESET = 'FORM_RESET';

// OVERLAY ACTIONS
export const OVERLAY_SET = 'OVERLAY_SET';
export const OVERLAY_UNSET = 'OVERLAY_UNSET';

// DASHBOARD ACTIONS
export const DASH_SELECTED_MENU = 'DASH_SELECTED_MENU';
